### ISSUE TITLE
Hibernate - Migrations - Flyway / Liquibase

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/banking-kata-java#35]
Evaluate pros and cons of Flyway vs Liquibase and implement one of these for our project

**Comment by thced** [comment]
I have split thoughts around this. :) 

For a demo, certainly. But once you hit a certain size; how and when would you run the tool in question? 

Can you accept downtime while running the tool (isolated), or do you take (relatively large) effort to migrate in small chunks so as to not have downtime?

**Comment by GuillaumeTaffin** [comment]
I am a bit puzzled by that need. I do not know where this project is aiming to but I thought it was a place to have some "bigger sized" example of clean architecture concepts.

I do not really get how using database migration tools serve this purpose. 

I even find it quite harmful from the perspective of a junior coming here to learn those concepts, and being actually submerged by all the accidental complexity clutter that is being put around it.

**Comment by valentinacupac** [comment]
@GuillaumeTaffin that is true - database migration tools are orthogonal, they are unrelated to HA, CA...

Why include it? Good question. The reason for including it is twofold: (a) on one hand, some kind of migration mechanism is needed by real life projects, so where does it fit in here, (b) suppose this GitHub repo is deployed and used for real (it may or may not be), then would need migrations too...

This is one difference between this GitHub repo as opposed to https://github.com/jmgarridopaz/bluezone which stay much more "pure" in illustrating just the concept and not the accidental complexity.

"I even find it quite harmful from the perspective of a junior coming here to learn those concepts" -> I agree with you. I find other repositories (e.g. bluezone, also Ivan Paulovich's work) to be much clearer in demonstrating the essence without clutter.... Whereas this GitHub repo (Banking Kata) is going in a different direction (in terms of adding some aspects that appear in real-life apps but are orthogonal to concepts illustrated); this was also motivated due to the audience gathered and the questions they ask....

**Comment by valentinacupac** [comment]
Related PR https://github.com/valentinacupac/banking-kata-java/pull/101

**Comment by GuillaumeTaffin** [comment]
@valentinacupac thanks for this clarification. Indeed, I was unsure of what the intent was, but applying "real world" tooling in that context makes sense as well.
