### ISSUE TITLE
GitHub Actions - Add static code analysis

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/banking-kata-java#38]

**Comment by rashed-08** [comment]
Is it already done?

**Comment by valentinacupac** [comment]
No, not done. Any tickets which are still in status "Open" means not done. We're also open to contributions https://github.com/valentinacupac/banking-kata-java/blob/main/CONTRIBUTING.md

**Comment by valentinacupac** [comment]
@rashed-08 if you're interested in contributing on this one, you can make a PR.
