### ISSUE TITLE
Adapter - Persistence - JDBC - SQL

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/banking-kata-java#98]
Add a module `adapter-persistence-jdbc-sql`. It should implement persistence using Postgres but not using JPA, instead using JDBC. Use raw SQL queries to execute commands.

For reference when creating the module, see `adapter-persistence-jpa` and `adapter-persistence-redis`. 

However, the difference here is that you'll be using JDBC rather than JPA.

**Comment by keremh** [comment]
hi @valentinacupac, can i work on this issue?

**Comment by valentinacupac** [comment]
Hi @keremh thanks for the question, I now saw another PR related to this ticket so this ticket is now closed, so feel free to see the other tickets.

P.S. I now updated CONTRIBUTING.md too, so that contributors can now choose any ticket to work on.
